#!/usr/bin/env bash
repo init -u https://android.googlesource.com/platform/manifest -b android-4.0.4_r2.1
mkdir -p .repo/local_manifests
curl https://raw.githubusercontent.com/MoltenMotherBoard/platform_local/aosp-ics/local_manifest.xml > .repo/local_manifests/mmb.xml
